/* Monsoon Field Notes: map-first editorial cartography, cream paper, rain-ink indigo, terracotta, muted gold. */
import { useMemo, useState } from "react";
import { ArrowDownRight, ArrowLeft, ArrowRight, BookOpen, Check, ChevronDown, Compass, Filter, Layers3, MapPin, Menu, Search, SlidersHorizontal, Sparkles, X } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";

type Region = "North India" | "South India" | "East India" | "West India" | "Central India" | "Northeast India";
type Location = { id:number; name:string; state:string; region:Region; period:string; categories:string[]; tradition:string; short:string; monuments:string[]; artists:string[]; context:string; characteristics:string; significance:string; fact:string; x:number; y:number; color:string };

const locations: Location[] = [
 {id:1,name:"Delhi",state:"Delhi",region:"North India",period:"Medieval / Early Modern",categories:["Islamic / Mughal Art","Architecture","Modern Indian Art"],tradition:"Mughal court culture & modern art",short:"A layered capital where Sultanate, Mughal, colonial, and contemporary practices meet.",monuments:["Humayun's Tomb","Red Fort","National Gallery of Modern Art"],artists:["Abdus Samad","Amrita Sher-Gil","M. F. Husain"],context:"Delhi's artistic landscape reflects successive imperial capitals and the institutions of independent India.",characteristics:"Geometric garden design, manuscript painting, monumental red sandstone, and modernist experimentation.",significance:"The city makes visible how patronage, power, and public institutions reshape artistic language.",fact:"Humayun's Tomb is an important precursor to the Mughal architectural vocabulary later seen at the Taj Mahal.",x:48,y:20,color:"indigo"},
 {id:2,name:"Agra",state:"Uttar Pradesh",region:"North India",period:"Early Modern",categories:["Islamic / Mughal Art","Architecture","Sculpture"],tradition:"Mughal architecture",short:"The imperial workshop-city of marble, pietra dura, gardens, and refined court craft.",monuments:["Taj Mahal","Agra Fort","Itimad-ud-Daulah's Tomb"],artists:["Ustad Ahmad Lahori","Ustad Isa Shirazi"],context:"As a Mughal capital, Agra concentrated architects, calligraphers, stonecutters, and painters from across the empire.",characteristics:"White marble, inlay, calligraphy, symmetry, charbagh gardens, and monumental thresholds.",significance:"Agra shows architecture as a synthesis of Persianate, Central Asian, and South Asian traditions.",fact:"The Taj Mahal's inlaid floral motifs use semi-precious stones set into marble.",x:53,y:25,color:"gold"},
 {id:3,name:"Mathura",state:"Uttar Pradesh",region:"North India",period:"Ancient / Classical",categories:["Buddhist Art","Sculpture","Hindu Temple Art"],tradition:"Mathura school of sculpture",short:"A major early centre for Buddhist, Jain, and Hindu images carved in red mottled sandstone.",monuments:["Kankali Tila","Mathura Museum"],artists:["Mathura workshop sculptors"],context:"From the Kushan period onward, Mathura's workshops helped establish durable image types for multiple faiths.",characteristics:"Red sandstone, robust bodies, frontal presence, and symbolic clarity.",significance:"The site reveals the shared workshop ecologies behind India's religious art traditions.",fact:"Mathura and Gandhara are often studied together in discussions of early Buddha imagery.",x:55,y:21,color:"terracotta"},
 {id:4,name:"Khajuraho",state:"Madhya Pradesh",region:"North India",period:"Medieval",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Chandela temple sculpture",short:"A sculptural ensemble where divine, courtly, natural, and everyday worlds animate temple walls.",monuments:["Kandariya Mahadeva Temple","Lakshmana Temple"],artists:["Chandela-period sthapatis"],context:"Built under the Chandela rulers between the 10th and 12th centuries, the temples form a carefully composed sacred landscape.",characteristics:"Vertical temple silhouettes, rhythmic bands of sculpture, sensuous bodies, and narrative detail.",significance:"Khajuraho demonstrates the temple as architecture, sculpture, and cosmology working together.",fact:"The surviving group is part of a larger historical complex of temples, many of which no longer remain.",x:48,y:32,color:"terracotta"},
 {id:5,name:"Jaipur",state:"Rajasthan",region:"North India",period:"Early Modern",categories:["Indian Painting","Architecture","Folk and Tribal Art"],tradition:"Rajput painting & urban design",short:"A planned court city known for miniature painting, astronomical architecture, and craft lineages.",monuments:["City Palace","Jantar Mantar","Hawa Mahal"],artists:["Sahibdin","Nihal Chand"],context:"Rajput courts supported painters who developed distinct visual languages around devotion, court life, and landscape.",characteristics:"Profile portraits, saturated mineral pigments, palace courtyards, and precise astronomical instruments.",significance:"Jaipur connects courtly image-making with living craft and urban planning traditions.",fact:"The city's historic pink surface treatment was associated with a 19th-century royal welcome.",x:43,y:27,color:"gold"},
 {id:6,name:"Amritsar",state:"Punjab",region:"North India",period:"Medieval / Early Modern",categories:["Architecture","Sculpture"],tradition:"Sikh architecture",short:"A sacred urban centre shaped by the Harmandir Sahib and an evolving tradition of devotional space.",monuments:["Harmandir Sahib","Akal Takht"],artists:["Sikh architectural and craft communities"],context:"The Golden Temple complex developed through layered patronage, rebuilding, and material embellishment.",characteristics:"Reflective water, gilded surfaces, calligraphic panels, and axial processional movement.",significance:"Amritsar shows how architecture can create a shared civic and spiritual identity.",fact:"The complex has entrances on all four sides, symbolizing openness to all communities.",x:38,y:13,color:"gold"},
 {id:7,name:"Mumbai",state:"Maharashtra",region:"West India",period:"Colonial / Modern",categories:["Colonial Art","Architecture","Modern Indian Art"],tradition:"Colonial urbanism & modern art",short:"A port city where Gothic revival, Art Deco, cinema, and modern art institutions intersect.",monuments:["Chhatrapati Shivaji Maharaj Terminus","Elephanta Caves","Kala Ghoda"],artists:["Raja Ravi Varma","F. N. Souza","Tyeb Mehta"],context:"Mumbai's cosmopolitan networks supported new publics, galleries, studios, and forms of mass visual culture.",characteristics:"Hybrid façades, civic monuments, modernist abstraction, and industrial-port textures.",significance:"The city is a key lens for understanding modernity, migration, and cultural production in India.",fact:"Mumbai's Art Deco buildings form one of the world's significant modern architectural ensembles.",x:33,y:49,color:"indigo"},
 {id:8,name:"Ajanta",state:"Maharashtra",region:"West India",period:"Ancient / Classical",categories:["Buddhist Art","Architecture","Indian Painting"],tradition:"Buddhist cave painting",short:"Horseshoe-shaped caves where murals, sculpture, and monastic architecture hold stories of compassion and past lives.",monuments:["Ajanta Caves"],artists:["Ajanta workshop communities"],context:"The caves were excavated and painted in phases, especially under Vakataka patronage in the 5th century CE.",characteristics:"Layered earth pigments, expressive eyes and gestures, narrative sequencing, and rock-cut interiors.",significance:"Ajanta preserves one of the most important bodies of early Indian mural painting.",fact:"Many paintings were made on prepared plaster over the excavated rock surface rather than directly on stone.",x:27,y:48,color:"moss"},
 {id:9,name:"Ellora",state:"Maharashtra",region:"West India",period:"Medieval",categories:["Buddhist Art","Hindu Temple Art","Sculpture","Architecture"],tradition:"Rock-cut pluralism",short:"A monumental ridge where Buddhist, Hindu, and Jain caves share one geological and cultural landscape.",monuments:["Kailasa Temple","Ellora Caves"],artists:["Rashtrakuta-period sculptors"],context:"Ellora's caves were created over centuries by communities working across religious traditions.",characteristics:"Excavated architecture, colossal relief, dramatic light, and multi-faith proximity.",significance:"Ellora makes pluralism tangible through shared labor, stone, and spatial memory.",fact:"The Kailasa temple is carved from a single mass of rock, excavated from the top downward.",x:28,y:54,color:"terracotta"},
 {id:10,name:"Udaipur",state:"Rajasthan",region:"West India",period:"Early Modern",categories:["Indian Painting","Architecture"],tradition:"Mewar miniature painting",short:"A lake city whose court ateliers developed luminous devotional and landscape painting.",monuments:["City Palace","Jagdish Temple"],artists:["Sahibdin","Manohar"],context:"Mewar painters worked for courts and temples, bringing epic, devotional, and seasonal subjects into intimate formats.",characteristics:"Flat color fields, lyrical landscapes, bold profiles, and jewel-like pigments.",significance:"Udaipur shows how miniature painting carries an entire visual world in a small frame.",fact:"Mewar painting is known for its early and sustained engagement with illustrated Hindu epics.",x:28,y:34,color:"gold"},
 {id:11,name:"Ahmedabad",state:"Gujarat",region:"West India",period:"Medieval / Modern",categories:["Folk and Tribal Art","Architecture","Modern Indian Art"],tradition:"Textile, pol house, and modern design",short:"A city of carved wood, stepwells, textile knowledge, and important modern design institutions.",monuments:["Sidi Saiyyed Mosque","Calico Museum of Textiles","Adalaj Stepwell"],artists:["Le Corbusier","Charles Correa"],context:"Ahmedabad's built and material culture connects mercantile patronage with vernacular craft and 20th-century design.",characteristics:"Jali screens, carved brackets, resist dyeing, woven pattern, and climate-conscious modernism.",significance:"The city demonstrates that design history lives in both monuments and everyday materials.",fact:"The Calico Museum is known for its significant collection of Indian textiles.",x:22,y:42,color:"moss"},
 {id:12,name:"Kolkata",state:"West Bengal",region:"East India",period:"Colonial / Modern",categories:["Colonial Art","Indian Painting","Modern Indian Art"],tradition:"Bengal School & modern art",short:"A colonial metropolis and intellectual centre where the Bengal School sought an Indian modernism.",monuments:["Victoria Memorial","Indian Museum","Government College of Art & Craft"],artists:["Abanindranath Tagore","Nandalal Bose","Jamini Roy"],context:"Artists and thinkers in Bengal debated the relationship between colonial academic realism, Asian traditions, and national culture.",characteristics:"Wash technique, lyrical line, spiritual symbolism, folk-derived forms, and literary exchange.",significance:"Kolkata is central to the story of how Indian artists negotiated modernity on their own terms.",fact:"Abanindranath Tagore's circle helped make the Bengal School a major force in early 20th-century Indian art.",x:69,y:42,color:"indigo"},
 {id:13,name:"Puri",state:"Odisha",region:"East India",period:"Medieval / Modern",categories:["Hindu Temple Art","Folk and Tribal Art","Indian Painting"],tradition:"Pattachitra & Jagannath culture",short:"A pilgrimage city where painted cloth, ritual image, and temple economy remain closely connected.",monuments:["Jagannath Temple","Raghurajpur artisan village"],artists:["Chitrakar families of Odisha"],context:"Pattachitra developed in relation to Jagannath worship and continues through hereditary workshop traditions.",characteristics:"Natural pigments, controlled contour, decorative borders, and narrative episodes.",significance:"Puri reveals how an art form can be both devotional practice and living livelihood.",fact:"Traditional Pattachitra often uses a prepared cloth surface called patta.",x:72,y:51,color:"terracotta"},
 {id:14,name:"Konark",state:"Odisha",region:"East India",period:"Medieval",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Kalinga temple architecture",short:"A monumental sun temple imagined as a celestial chariot, dense with sculptural movement.",monuments:["Sun Temple at Konark"],artists:["Eastern Ganga-period sthapatis"],context:"Built in the 13th century under Narasimhadeva I, Konark represents the mature Kalinga style.",characteristics:"Chariot wheels, sculpted narrative bands, dynamic stone bodies, and axial monumentality.",significance:"Konark shows how architecture can turn cosmology, time, and royal power into stone.",fact:"The temple's sculpted wheels are among its most recognisable visual features.",x:73,y:54,color:"gold"},
 {id:15,name:"Bhubaneswar",state:"Odisha",region:"East India",period:"Ancient / Medieval",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Kalinga temple city",short:"A dense sacred landscape of rekha deuls, sculpted gateways, and evolving temple forms.",monuments:["Lingaraja Temple","Mukteshwar Temple","Rajarani Temple"],artists:["Kalinga temple artisans"],context:"Bhubaneswar preserves a sequence of temple experiments that clarify the development of Odisha's architectural idiom.",characteristics:"Curving towers, sculpted doorways, guardian figures, and controlled vertical rhythm.",significance:"The city operates as an open-air study of architectural evolution.",fact:"The Mukteshwar Temple is often noted for its richly ornamented torana gateway.",x:69,y:48,color:"terracotta"},
 {id:16,name:"Bishnupur",state:"West Bengal",region:"East India",period:"Medieval / Early Modern",categories:["Hindu Temple Art","Architecture","Folk and Tribal Art"],tradition:"Terracotta temple art",short:"A Bengal town famous for brick temples whose terracotta panels animate epic and social scenes.",monuments:["Rasmancha","Jor Bangla Temple","Madanmohan Temple"],artists:["Bishnupur terracotta artisans"],context:"Malla court patronage encouraged a distinctive temple vocabulary using local brick and fired clay.",characteristics:"Curved roof forms, narrative terracotta plaques, repeating ornament, and warm red surfaces.",significance:"Bishnupur demonstrates how regional materials can produce a highly recognisable architecture.",fact:"Terracotta panels often include both mythological scenes and glimpses of contemporary life.",x:65,y:38,color:"terracotta"},
 {id:17,name:"Sanchi",state:"Madhya Pradesh",region:"Central India",period:"Ancient / Classical",categories:["Buddhist Art","Sculpture","Architecture"],tradition:"Buddhist stupa architecture",short:"A hilltop complex where gateways, railings, and the stupa shape a ritual path through history.",monuments:["Great Stupa","Sanchi toranas"],artists:["Mauryan and later artisan communities"],context:"The site grew from Ashokan patronage and was expanded by later dynasties over centuries.",characteristics:"Processional circumambulation, carved railings, symbolic narrative, and stone translation of timber forms.",significance:"Sanchi offers a foundational lesson in how Buddhist architecture directs movement and memory.",fact:"Early Buddhist art at Sanchi often represents the Buddha through symbols rather than a human figure.",x:49,y:47,color:"moss"},
 {id:18,name:"Bhimbetka",state:"Madhya Pradesh",region:"Central India",period:"Prehistoric",categories:["Folk and Tribal Art","Ancient Art"],tradition:"Rock shelter painting",short:"Shelters that hold one of the longest visual records of human presence in the Indian subcontinent.",monuments:["Bhimbetka rock shelters"],artists:["Prehistoric painting communities"],context:"The shelters preserve paintings made across long periods, including scenes of animals, hunting, ritual, and social life.",characteristics:"Mineral pigments, rhythmic outlines, layered surfaces, and movement across rock walls.",significance:"Bhimbetka links art history to deep time, ecology, and the human impulse to mark shared experience.",fact:"The site includes hundreds of shelters, many with paintings from different periods.",x:46,y:53,color:"moss"},
 {id:19,name:"Bhopal",state:"Madhya Pradesh",region:"Central India",period:"Modern / Contemporary",categories:["Folk and Tribal Art","Modern Indian Art"],tradition:"Tribal art & museum practice",short:"A contemporary cultural hub for the preservation and presentation of Adivasi visual traditions.",monuments:["Museum of Man","Bharat Bhavan"],artists:["Jangarh Singh Shyam","Durgabai Vyam"],context:"Bhopal's institutions have helped bring Gond and other indigenous art practices into national and international conversations.",characteristics:"Living lineages, animal cosmologies, dense pattern, and translation between wall, paper, and gallery.",significance:"The city raises important questions about authorship, community, museum display, and living tradition.",fact:"Bharat Bhavan was designed as a multidisciplinary arts centre rather than a conventional single-collection museum.",x:44,y:49,color:"indigo"},
 {id:20,name:"Chennai",state:"Tamil Nadu",region:"South India",period:"Colonial / Modern",categories:["Colonial Art","Modern Indian Art","Indian Painting"],tradition:"Madras School & craft",short:"A coastal centre for art education, modernism, bronze casting, and South Indian cultural institutions.",monuments:["Government Museum, Egmore","Cholamandal Artists' Village"],artists:["K. C. S. Paniker","S. Dhanapal"],context:"The Madras School shaped a distinctive modernist language grounded in line, material, and regional visual culture.",characteristics:"Graphic line, restrained palette, symbolic abstraction, and craft-based experimentation.",significance:"Chennai shows how regional art schools can produce influential versions of Indian modernism.",fact:"Cholamandal Artists' Village became an important artist-led community in the history of Indian modern art.",x:57,y:73,color:"indigo"},
 {id:21,name:"Thanjavur",state:"Tamil Nadu",region:"South India",period:"Medieval / Early Modern",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Chola bronze & temple art",short:"A Chola legacy of soaring temples, processional bronze images, and precise devotional craft.",monuments:["Brihadisvara Temple","Thanjavur Maratha Palace"],artists:["Chola sthapatis","Kumbakonam bronze-casting communities"],context:"Royal patronage and temple economies supported ambitious architecture and the celebrated lost-wax bronze tradition.",characteristics:"Granite scale, balanced bronze bodies, expressive gesture, and ritual mobility.",significance:"Thanjavur makes clear that sculpture is not only an object but also a moving participant in ceremony.",fact:"The Nataraja image is one of the most studied forms in the Chola bronze tradition.",x:54,y:80,color:"gold"},
 {id:22,name:"Mahabalipuram",state:"Tamil Nadu",region:"South India",period:"Classical / Medieval",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Pallava rock-cut art",short:"Sea-facing monuments where Pallava architects turned boulders and cliffs into narrative sculpture.",monuments:["Shore Temple","Pancha Rathas","Descent of the Ganges"],artists:["Pallava sculptors"],context:"The site records experiments in cave, monolithic, and structural temple forms under Pallava patronage.",characteristics:"Granite relief, monolithic rathas, open-air narrative, and coastal light.",significance:"Mahabalipuram is a field lesson in how a regional workshop develops new architectural types.",fact:"The site contains both excavated cave temples and free-standing monolithic forms.",x:58,y:69,color:"terracotta"},
 {id:23,name:"Hampi",state:"Karnataka",region:"South India",period:"Medieval",categories:["Hindu Temple Art","Sculpture","Architecture"],tradition:"Vijayanagara urbanism",short:"A monumental riverine capital of bazaars, mandapas, shrines, and granite landscapes.",monuments:["Virupaksha Temple","Vittala Temple","Royal Enclosure"],artists:["Vijayanagara artisan communities"],context:"Hampi's remains reveal a powerful empire's religious, commercial, and civic spaces across a dramatic boulder field.",characteristics:"Granite colonnades, musical pillars, processional streets, and landscape-scale planning.",significance:"Hampi expands the idea of a monument into an entire urban and ecological system.",fact:"The Vittala complex is known for its stone chariot and highly ornamented pillared halls.",x:43,y:69,color:"gold"},
 {id:24,name:"Badami",state:"Karnataka",region:"South India",period:"Classical / Medieval",categories:["Hindu Temple Art","Buddhist Art","Sculpture","Architecture"],tradition:"Chalukya cave temples",short:"A sandstone basin where Chalukya builders explored cave, structural, and sculptural forms.",monuments:["Badami Cave Temples","Agastya Lake"],artists:["Early Chalukya sculptors"],context:"Badami's caves and nearby sites form a major chapter in the development of Deccan temple architecture.",characteristics:"Red sandstone, cave reliefs, hybrid plans, and sculptural bodies integrated with rock.",significance:"The site shows the Deccan as a zone of experimentation and cultural exchange.",fact:"The cave complex includes imagery associated with Shaiva, Vaishnava, and Jain traditions.",x:39,y:63,color:"terracotta"},
 {id:25,name:"Mysuru",state:"Karnataka",region:"South India",period:"Early Modern / Modern",categories:["Indian Painting","Architecture","Folk and Tribal Art"],tradition:"Mysore painting & palace culture",short:"A courtly centre where luminous gold-ground painting meets palace architecture and living festival craft.",monuments:["Mysore Palace","Jaganmohan Palace Art Gallery"],artists:["Mysore painting workshop traditions"],context:"The Wodeyar court supported painting, music, architecture, and ritual arts that continue to shape the city's identity.",characteristics:"Gesso relief, gold leaf, delicate line, jewel tones, and devotional iconography.",significance:"Mysuru demonstrates how court traditions survive by adapting to new publics and institutions.",fact:"Mysore painting is especially associated with a finely worked gold relief surface.",x:40,y:76,color:"gold"},
];

const categoryOptions = ["All categories","Ancient Art","Buddhist Art","Hindu Temple Art","Islamic / Mughal Art","Indian Painting","Sculpture","Architecture","Folk and Tribal Art","Colonial Art","Modern Indian Art"];
const periodOptions = ["All periods","Prehistoric","Ancient","Classical","Medieval","Early Modern","Colonial","Modern / Contemporary"];
const regionOptions = ["All regions","North India","South India","East India","West India","Central India","Northeast India"];
const traditions = [
 {name:"Buddhist Art",desc:"Stupas, caves, murals, and symbols of the awakened life.",count:"04 sites",color:"moss"},
 {name:"Temple Sculpture",desc:"Stone bodies, sacred thresholds, and architecture in motion.",count:"11 sites",color:"terracotta"},
 {name:"Mughal Miniature Painting",desc:"Manuscripts, gardens, courtly observation, and detail.",count:"02 sites",color:"gold"},
 {name:"Rajput Painting",desc:"Devotion, epic, and landscape in jewel-like pigment.",count:"02 sites",color:"gold"},
 {name:"Pahari Painting",desc:"Poetry, music, and intimate mountain worlds.",count:"Explore region",color:"indigo"},
 {name:"Bengal School",desc:"A search for an Indian modernism through wash and line.",count:"01 site",color:"indigo"},
 {name:"Folk & Tribal Art",desc:"Living practices rooted in community, ritual, and place.",count:"07 sites",color:"moss"},
 {name:"South Indian Bronze",desc:"The moving image: devotion cast in luminous metal.",count:"03 sites",color:"terracotta"},
 {name:"Indian Modern Art",desc:"New publics, new materials, and many modernities.",count:"06 sites",color:"indigo"},
];

function MapArtwork({items,active,onSelect,zoom,setZoom}:{items:Location[];active:Location|null;onSelect:(l:Location)=>void;zoom:number;setZoom:(z:number)=>void}) {
 return <div className="map-frame">
   <div className="map-toolbar"><span className="map-scale">20°N</span><div className="zoom-controls"><button onClick={()=>setZoom(Math.min(1.35,zoom+.12))} aria-label="Zoom in">+</button><button onClick={()=>setZoom(Math.max(.9,zoom-.12))} aria-label="Zoom out">−</button></div></div>
   <svg viewBox="0 0 100 100" className="india-map" style={{transform:`scale(${zoom})`}} role="img" aria-label="Interactive stylised map of India">
    <defs><filter id="map-shadow"><feDropShadow dx="0" dy=".8" stdDeviation=".6" floodOpacity=".18"/></filter><pattern id="grid" width="8" height="8" patternUnits="userSpaceOnUse"><path d="M8 0H0V8" fill="none" stroke="#24324b" strokeOpacity=".12" strokeWidth=".16"/></pattern></defs>
    <rect width="100" height="100" fill="url(#grid)"/>
    <path d="M43 6 L51 7 55 12 61 14 62 21 70 25 77 35 79 43 75 49 73 58 68 63 65 75 59 88 54 94 48 90 45 83 40 77 36 67 30 60 25 50 20 44 23 37 28 33 32 26 35 19 39 16Z" fill="#eee4d2" stroke="#7f806f" strokeWidth=".65" filter="url(#map-shadow)"/>
    <path d="M46 7 L47 92 M25 40 Q49 48 77 40 M30 62 Q52 67 70 62" fill="none" stroke="#b69c72" strokeDasharray="1.4 1.5" strokeWidth=".28" opacity=".7"/>
    <path d="M31 24 Q41 30 47 26 T63 26 M31 69 Q43 64 56 69 T70 67" fill="none" stroke="#24324b" strokeOpacity=".18" strokeWidth=".45"/><g className="map-annotations" fill="#24324b" opacity=".58" fontFamily="Manrope, sans-serif" fontSize="2.1" letterSpacing=".22"><text x="41" y="17">NORTH</text><text x="24" y="47">WEST</text><text x="62" y="45">EAST</text><text x="47" y="60">CENTRAL</text><text x="47" y="84">SOUTH</text><text x="27" y="92">ARABIAN SEA</text><text x="75" y="64">BAY OF BENGAL</text></g><g fill="#65775b" opacity=".7" fontFamily="Manrope, sans-serif" fontSize="1.55" letterSpacing=".12"><text x="44" y="23">DELHI</text><text x="48" y="35">KHAJURAHO</text><text x="24" y="51">AJANTA</text><text x="68" y="52">KONARK</text><text x="52" y="82">THANJAVUR</text></g>
    {items.map(loc=><g key={loc.id} className={`marker ${active?.id===loc.id?"marker-active":""}`} transform={`translate(${loc.x},${loc.y})`} onClick={()=>onSelect(loc)} onKeyDown={e=>e.key==='Enter'&&onSelect(loc)} tabIndex={0} role="button" aria-label={`Open ${loc.name}`}>
      <circle r={active?.id===loc.id?2.3:1.55} fill={loc.color==='terracotta'? '#b4553c':loc.color==='gold'?'#b88a3b':loc.color==='moss'?'#65775b':'#24324b'} stroke="#f7f2e8" strokeWidth=".7"/><circle r=".42" fill="#f7f2e8"/><title>{loc.name}</title>
      {active?.id===loc.id&&<circle r="3.3" fill="none" stroke="#b4553c" strokeWidth=".35" className="pulse-ring"/>}
    </g>)}
   </svg>
   <div className="map-compass"><Compass size={18}/><span>N</span></div>
   <div className="map-caption"><span>Field map / 25 marked places</span><span>Source: UNESCO, ASI & institutional collections</span></div>
 </div>
}

export default function Home(){
 const [query,setQuery]=useState(""); const [category,setCategory]=useState("All categories"); const [period,setPeriod]=useState("All periods"); const [region,setRegion]=useState("All regions"); const [active,setActive]=useState<Location|null>(null); const [zoom,setZoom]=useState(1); const [mobileNav,setMobileNav]=useState(false);
 const filtered=useMemo(()=>locations.filter(l=>{const hay=[l.name,l.state,l.tradition,l.monuments.join(" "),l.artists.join(" "),l.short].join(" ").toLowerCase(); return (!query||hay.includes(query.toLowerCase()))&&(category==="All categories"||l.categories.includes(category)|| (category==="Ancient Art"&&l.period.includes("Ancient")))&&(period==="All periods"||l.period.includes(period))&&(region==="All regions"||l.region===region)}),[query,category,period,region]);
 const activeIndex=active?filtered.findIndex(l=>l.id===active.id):-1;
 const reset=()=>{setQuery("");setCategory("All categories");setPeriod("All periods");setRegion("All regions");setActive(null)};
 const focusTradition=(name:string)=>{setCategory(name==="Temple Sculpture"?"Sculpture":name==="South Indian Bronze"?"Sculpture":name); document.getElementById("explore-map")?.scrollIntoView({behavior:"smooth"})};
 return <div className="site-shell">
  <header className="topbar"><a className="brand" href="#top"><span className="brand-mark"><img src="/manus-storage/mapping-indian-art-mark_2e8a9a8f.png" alt=""/></span><span><strong>Mapping Indian Art</strong><small>An interactive cultural atlas</small></span></a><button className="mobile-menu" onClick={()=>setMobileNav(!mobileNav)} aria-label="Toggle menu"><Menu size={22}/></button><nav className={mobileNav?"nav-open":""}><a href="#explore-map">Explore map</a><a href="#traditions">Art traditions</a><a href="#locations">Locations</a><a href="#about">About</a><a href="#sources">Sources</a></nav><div className="topbar-meta"><span className="edition">CO1 · INDIAN ART HISTORY</span><span className="issue">FIELD GUIDE 01</span></div></header>
  <main id="top">
   <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="eyebrow-line"></span> A spatial field guide</p><h1>Follow the<br/><em>pigment,</em><br/>stone by stone.</h1><p className="hero-intro">Explore the places, traditions, artists, monuments, and movements that shaped India's artistic heritage.</p><a href="#explore-map" className="hero-cta">Explore the map <ArrowDownRight size={17}/></a><div className="hero-note"><span>01</span><p>Indian art is not a single story.<br/>It is a geography of many voices.</p></div></div><div className="hero-visual"><img src="/manus-storage/mapping-indian-art-hero_5af934e6.jpg" alt="Archival collage of Indian art and a map of India"/><div className="hero-stamp">25<br/><small>PLACES<br/>MARKED</small></div><div className="hero-caption">A living atlas / भारत का कला मानचित्र</div></div></section>
   <section className="stats-strip"><div><strong>25</strong><span>marked places</span></div><div><strong>18</strong><span>art traditions</span></div><div><strong>7</strong><span>historical periods</span></div><div><strong>19</strong><span>states & territories</span></div><p>From prehistoric shelters<br/>to contemporary studios.</p></section>
   <section className="explore-section" id="explore-map"><div className="section-kicker"><span>02 / THE ATLAS</span><span>Explore by geography</span></div><div className="section-heading"><div><h2>Begin anywhere.<br/><em>Place the story.</em></h2></div><p>Each marker opens a field note: a compact, sourced introduction to the artistic life of a place. Filter by what you want to notice first.</p></div>
    <div className="map-layout"><aside className="filter-panel"><div className="panel-title"><span><SlidersHorizontal size={17}/> Refine the map</span><button onClick={reset}>Reset</button></div><label className="searchbox"><Search size={17}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search place, artist, artwork..."/><kbd>⌘ K</kbd></label><div className="filter-group"><label>Art category</label><select value={category} onChange={e=>setCategory(e.target.value)}>{categoryOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><label>Historical period</label><select value={period} onChange={e=>setPeriod(e.target.value)}>{periodOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-group"><label>Region</label><select value={region} onChange={e=>setRegion(e.target.value)}>{regionOptions.map(x=><option key={x}>{x}</option>)}</select></div><div className="filter-summary"><strong>{filtered.length}</strong><span>of {locations.length} places visible</span></div><div className="legend"><p>Marker key</p><span><i className="dot dot-terracotta"></i> Temple / sculpture</span><span><i className="dot dot-gold"></i> Court / architecture</span><span><i className="dot dot-moss"></i> Buddhist / folk</span><span><i className="dot dot-indigo"></i> Modern / colonial</span></div></aside><div className="map-stage"><MapArtwork items={filtered} active={active} onSelect={setActive} zoom={zoom} setZoom={setZoom}/>{filtered.length===0&&<div className="map-empty"><MapPin size={28}/><strong>No places match yet.</strong><button onClick={reset}>Clear filters</button></div>}<div className="map-result">{active?<><span>Selected place</span><strong>{active.name}</strong></>:<><span>Click a marker to open</span><strong>A field note</strong></>}</div></div></div>
   </section>
   <section className="location-rail" id="locations"><div className="rail-heading"><div><span className="section-label">03 / LOCATION INDEX</span><h2>Places worth<br/><em>lingering over.</em></h2></div><p>Use the index as a second way into the map. Every place is a node in a larger network of materials, patrons, makers, and memory.</p></div><div className="location-cards">{locations.slice(0,6).map((l,i)=><button className="location-card" key={l.id} onClick={()=>{setActive(l);document.getElementById("explore-map")?.scrollIntoView({behavior:"smooth"})}}><span className="card-index">0{i+1}</span><span className="card-place">{l.region}</span><h3>{l.name}</h3><p>{l.tradition}</p><ArrowRight size={17}/></button>)}</div></section>
   <section className="traditions-section" id="traditions"><div className="section-kicker"><span>04 / CONSTELLATIONS</span><span>Explore art traditions</span></div><div className="traditions-intro"><h2>Many practices.<br/><em>One living map.</em></h2><p>Choose a thread and watch the geography gather around it.</p></div><div className="tradition-grid">{traditions.map(t=><button key={t.name} className={`tradition-card ${t.color}`} onClick={()=>focusTradition(t.name)}><span className="tradition-icon"><Layers3 size={18}/></span><span className="tradition-count">{t.count}</span><span className="tradition-code">ATLAS ENTRY / {String(traditions.indexOf(t)+1).padStart(2,"0")}</span><h3>{t.name}</h3><p>{t.desc}</p><span className="tradition-source">FIELD NOTE · CULTURAL PRACTICE</span><span className="tradition-action">Show on map <ArrowRight size={15}/></span></button>)}</div></section>
   <section className="about-section" id="about"><div className="about-art"><div className="about-glyph"><Compass size={62} strokeWidth={1}/></div><span>SPACE / MEMORY / MATERIAL</span></div><div className="about-copy"><span className="section-label">05 / WHY A MAP?</span><h2>Art history<br/><em>has coordinates.</em></h2><p>A temple is not only a date. A painting is not only a style. Each work belongs to a place: its stone, climate, workshop, patron, route, and community. This atlas uses geography as the first question.</p><p>Built for Indian Art History (CO1), this exhibition is a starting point for looking closer and researching further.</p><a href="#sources">Read the sources <ArrowRight size={16}/></a></div></section>
   <section className="sources-section" id="sources"><div><span className="section-label">06 / FURTHER READING</span><h2>Keep<br/><em>following.</em></h2></div><div className="sources-copy"><p>The map is an educational synthesis. For deeper study, begin with the institutions and collections below.</p><ol><li><a href="https://whc.unesco.org/en/list/" target="_blank" rel="noreferrer">UNESCO World Heritage Centre</a><span>Sites, statements of significance, and conservation context.</span></li><li><a href="https://asi.nic.in/" target="_blank" rel="noreferrer">Archaeological Survey of India</a><span>Protected monuments and archaeological documentation.</span></li><li><a href="https://www.metmuseum.org/toah/" target="_blank" rel="noreferrer">The Metropolitan Museum of Art · Heilbrunn Timeline</a><span>Accessible essays on Indian art and material culture.</span></li><li><a href="https://artsandculture.google.com/" target="_blank" rel="noreferrer">Google Arts & Culture</a><span>Digital collections and institutional exhibitions.</span></li></ol></div></section>
  </main>
  <footer><a className="brand" href="#top"><span className="brand-mark"><img src="/manus-storage/mapping-indian-art-mark_2e8a9a8f.png" alt=""/></span><span><strong>Mapping Indian Art</strong><small>An interactive cultural atlas</small></span></a><span>Made for looking closer.</span><span>© 2026 · CO1</span></footer>
  {active&&<div className="detail-overlay" onClick={e=>e.target===e.currentTarget&&setActive(null)}><aside className="detail-panel"><div className="detail-top"><span className="section-label">FIELD NOTE / {String(active.id).padStart(2,"0")}</span><button className="close-btn" onClick={()=>setActive(null)} aria-label="Close detail panel"><X size={19}/></button></div><div className="detail-hero"><div><span>{active.region}</span><h2>{active.name}</h2><p>{active.state} · {active.period}</p></div><div className={`detail-badge ${active.color}`}><MapPin size={19}/></div></div><div className="detail-scroll"><div className="detail-lead"><span className="label">Art tradition</span><h3>{active.tradition}</h3><p>{active.short}</p></div><div className="detail-grid"><div><span className="label">Why it matters</span><p>{active.significance}</p></div><div><span className="label">Historical context</span><p>{active.context}</p></div><div><span className="label">Major monuments / works</span><p>{active.monuments.join(" · ")}</p></div><div><span className="label">Artists / schools</span><p>{active.artists.join(" · ")}</p></div></div><div className="fact-box"><Sparkles size={17}/><div><span className="label">Did you know?</span><p>{active.fact}</p></div></div><div className="detail-character"><span className="label">Artistic characteristics</span><p>{active.characteristics}</p></div></div><div className="detail-nav"><button disabled={activeIndex<=0} onClick={()=>setActive(filtered[activeIndex-1])}><ArrowLeft size={15}/> Previous</button><span>{activeIndex+1} / {filtered.length}</span><button disabled={activeIndex===filtered.length-1} onClick={()=>setActive(filtered[activeIndex+1])}>Next <ArrowRight size={15}/></button></div></aside></div>}
 </div>
}
